name=timersapi
version=1.0.3
author=WolodiaM <w.melnyk07@gmail.com>
maintainer=WolodiaM <w.melnyk07@gmail.com>
sentence=Library for timers, countdowns and counters.
paragraph=Has different settings for all types of timers.
category=Timing
url=https://github.com/WolodiaM/timersapi-library
architectures=* 
includes=timersapi.hpp



